### ISSUE TITLE
Issue about file 3_extract_results.py

### ISSUE THREAD

**Issue by davidepettinari** [fusion-energy/magnetic_fusion_openmc_dagmc_paramak_example#11]
Good evening, I apologize for the inconvenience. In the file **3_extract_results.py** at line 41 there is: `tally=tbr_mesh_tally`. Since this part of code has the function of writing the heating mesh tally as a vtk file, I think it should be: `tally=heating_mesh_tally`.
Thanks for your attention. 
Kind regards, 
Davide

**Comment by shimwell** [comment]
Thanks Davide for letting me know. Would you be interested in making a pull request for fix.

**Comment by davidepettinari** [comment]
Yes, I do that now.
